#version: "3.7"
networks:
  default:
services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      #- JELLYFIN_PublishedServerUrl=http://192.168.2.79 #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel-24.35.30872.22
    networks:
      - default
    volumes:
      - /mediaserver/docker/jellyfin/:/config
      - /mediaserver/media:/mediaserver/media
      # exemple: -/docker/appdata/radarr:/config   si    - /data:/data
    devices:
      - /dev/dri:/dev/dri 
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
      #restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - default
    ports:
      - 8989:8989
    restart: always
    volumes:
      - /mediaserver/docker/sonarr:/config
      - /mediaserver:/mediaserver
    links:
      - nzbhydra
      - nzbget

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - default
    ports:
      - 7878:7878
    volumes:
      - /mediaserver/docker/radarr:/config  
      - /mediaserver:/mediaserver
    links:
      - nzbhydra
      - nzbget

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mediaserver/docker/lidarr:/config
      - /mediaserver/:/mediaserver
    ports:
      - 8686:8686
    restart: always   

  navidrome:
    image: deluan/navidrome:latest
      #user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: always
    container_name: navidrome  
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - /mediaserver/docker/navidrome:/data
      - /mediaserver/media:/mediaserver/media 

  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: lidatube
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mediaserver/docker/lidatube:/config
      - /mediaserver/media/music:/lidatube/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    restart: unless-stopped
      
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Bucharest
        #- PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /mediaserver/docker/jellyseerr:/config
      - /mediaserver:/mediaserver  
    restart: always
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - default
    ports:
      - 9696:9696
    restart: always
    volumes:
      - /mediaserver/docker/prowlarr:/config
      - /mediaserver:/mediaserver

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mediaserver/docker/qbittorrent:/config
      - /mediaserver/downloads:/mediaserver/downloads 
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - default
    ports:
      - 6789:6789
    volumes:
      - /mediaserver/docker/nzbget:/config
      - /mediaserver/usenet:/mediaserver/usenet

  nzbhydra:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - default
    ports:
      - 5076:5076
    volumes:
      - /mediaserver/docker/nzbhydra:/config
      - /mediaserver/usenet:/mediaserver/usenet
  
  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /mediaserver/docker/dokemondata:/data
      - /var/run/docker.sock:/var/run/docker.sock

  wyl:
    image: aceberg/watchyourlan
    container_name: wyl
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /mediaserver/docker/wyl:/data/WatchYourLAN
    environment:
      TZ: Europe/Bucharest              # required: needs your TZ for correct time
      IFACES: "eno1"  # required: 1 or more interface
      HOST: "192.168.2.79"                   # optional, default: 0.0.0.0
      PORT: "8840"                      # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 120
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "sand"                     # optional
      COLOR: "dark"                     # optional

